// Package catalog holds the schema metadata: which tables exist, what columns
// they have, and what constraints apply.
//
// The catalog is plain in-memory structs. It is deliberately not stored as
// ordinary tables that DDL inserts rows into, because that makes every CREATE
// TABLE take data locks on a shared relation and turns a catalog update into a
// query that can fail halfway. information_schema and pg_catalog are instead
// exposed as read-only views computed from these structs.
package catalog

import (
	"cmp"
	"hash/maphash"
	"slices"
	"strconv"
	"strings"
	"sync"

	"github.com/oxisto/lightsql/internal/ast"
	"github.com/oxisto/lightsql/internal/pgerr"
	"github.com/oxisto/lightsql/internal/storage"
	"github.com/oxisto/lightsql/internal/types"
	"github.com/oxisto/lightsql/internal/wal"
)

// DefaultSchema is the schema a name resolves to when written unqualified.
const DefaultSchema = "public"

// Identity records whether a column is an identity column, and which form.
//
// It is separate from Type.Serial, which says only that the column draws from a
// sequence. Both identity forms do that; what distinguishes them is whether a
// statement may supply a value of its own, which is a question about statements
// rather than about the type.
type Identity uint8

const (
	// NotIdentity is an ordinary column, including one declared SERIAL.
	NotIdentity Identity = iota
	// IdentityByDefault is GENERATED BY DEFAULT AS IDENTITY: the sequence
	// supplies a value when the statement does not, exactly like SERIAL.
	IdentityByDefault
	// IdentityAlways is GENERATED ALWAYS AS IDENTITY: the sequence always
	// supplies the value, and a statement offering one is refused.
	IdentityAlways
)

// Column is one column of a table.
type Column struct {
	Name string
	Type Type
	// NotNull is set by a NOT NULL constraint or implied by PRIMARY KEY.
	NotNull bool
	// Identity records an identity column; see Identity.
	Identity Identity
	// PrimaryKey marks membership of the table's primary key. It is a hint for
	// introspection only; the constraint itself lives in Table.Constraints,
	// because a key over several columns is one constraint on the combination
	// rather than one per column.
	PrimaryKey bool
	// Missing is the value a row stored before this column existed takes.
	//
	// ADD COLUMN does not rewrite the rows already in the heap: a version's
	// values are never mutated once it is linked in, which is what lets a
	// reader hold one without copying. Rows written earlier are therefore
	// shorter than the table, and the columns they lack read as this value.
	// PostgreSQL does the same thing under the name attmissingval.
	//
	// It is the zero Value for a column that has always existed, which reads as
	// NULL and is what a row missing it should say anyway.
	Missing types.Value
	// Default is the DEFAULT expression as written, or nil when the column has
	// none.
	//
	// The catalog holds the syntax rather than a bound expression because the
	// binder and the plan both sit above it; storing a plan expression here
	// would invert that. Each statement binds it afresh, which costs one bind
	// per statement rather than per row.
	Default ast.Expr
}

// ConstraintKind distinguishes a primary key from an ordinary unique
// constraint. They are enforced identically; only the reported name differs.
type ConstraintKind uint8

const (
	// PrimaryKeyConstraint is the table's primary key, of which there is at
	// most one. Its columns are implicitly NOT NULL.
	PrimaryKeyConstraint ConstraintKind = iota
	// UniqueConstraint is a UNIQUE constraint. Unlike a primary key, its
	// columns may be NULL.
	UniqueConstraint
)

func (k ConstraintKind) String() string {
	if k == PrimaryKeyConstraint {
		return "primary key"
	}
	return "unique"
}

// Constraint is a uniqueness requirement over one or more columns.
//
// Columns holds ordinals rather than names, and the constraint covers their
// combination. Modelling this as a flag on each column instead would make
// PRIMARY KEY (a, b) mean "a is unique and b is unique", which is a strictly
// stronger and wrong requirement.
type Constraint struct {
	// Name is the constraint name, either as written after CONSTRAINT or
	// derived in PostgreSQL's style, e.g. users_pkey or users_email_key.
	Name    string
	Kind    ConstraintKind
	Columns []int
}

// RefAction is what happens to a referencing row when the row it points at is
// deleted or has its key updated.
type RefAction uint8

const (
	// NoAction and Restrict both refuse the change while references remain.
	// PostgreSQL distinguishes them by when the check runs — NO ACTION can be
	// deferred to end of transaction — but lightsql has no deferred
	// constraints, so the two behave identically and the pair is kept only so
	// that a schema reads back as it was written.
	NoAction RefAction = iota
	Restrict
	// Cascade applies the change to the referencing rows too.
	Cascade
	// SetNull clears the referencing columns.
	SetNull
	// SetDefault puts the referencing columns back to their DEFAULT.
	SetDefault
)

var refActionNames = [...]string{
	NoAction: "NO ACTION", Restrict: "RESTRICT", Cascade: "CASCADE",
	SetNull: "SET NULL", SetDefault: "SET DEFAULT",
}

func (a RefAction) String() string { return refActionNames[a] }

// ForeignKey requires that this table's Columns match a row of Parent.
//
// Both sides are ordinals, resolved once when the table is created, so
// enforcement never looks a name up again.
type ForeignKey struct {
	Name    string
	Columns []int
	// Parent is the referenced table, and ParentCols the columns matched
	// against. They must carry a primary key or unique constraint, or a
	// reference could match several rows and the actions below would be
	// ambiguous.
	Parent     *Table
	ParentCols []int
	OnDelete   RefAction
	OnUpdate   RefAction
}

// Referencing is a foreign key pointing *at* a table, held by the table it
// points at.
//
// A delete or key update has to find every table that references the one being
// changed, and searching the whole catalog per statement would make the cost of
// a delete depend on how many unrelated tables exist.
type Referencing struct {
	Child *Table
	FK    *ForeignKey
}

// Index is a secondary index.
//
// lightsql builds no physical structure for one: there is no index selection in
// the planner yet, so a plain index changes nothing a query can observe and is
// recorded only so that a schema reads back as it was written. A UNIQUE index
// is different -- it is a constraint, enforced like any other.
//
// Where holds a partial index's predicate as written; see Column.Default for
// why the catalog stores syntax rather than a bound expression. A row the
// predicate does not select is not covered by the index, so a unique partial
// index constrains only the rows it applies to.
type Index struct {
	Name    string
	Columns []int
	Unique  bool
	Where   ast.Expr
}

// Check is a CHECK constraint: a predicate over a single row.
//
// It is kept apart from Constraint because the two are enforced by different
// machinery — a uniqueness constraint compares rows against each other, while a
// check evaluates an expression over one row and never looks at the others.
type Check struct {
	Name string
	// Expr is the predicate as written; see Column.Default for why the catalog
	// stores syntax rather than a bound expression.
	Expr ast.Expr
}

// Table is a table definition together with its data.
//
// Definition and storage live in one struct because a table's rows are only ever
// reached through its definition, and separating them would mean every access
// carried a pair of pointers that must not disagree.
type Table struct {
	Schema string
	Name   string

	Columns []Column
	// Constraints are the table's uniqueness constraints, checked on every
	// insert and update.
	Constraints []Constraint
	// Checks are the table's CHECK constraints, evaluated per row.
	Checks []Check
	// ForeignKeys are the references this table makes to others.
	ForeignKeys []ForeignKey
	// Indexes are the secondary indexes declared on this table.
	Indexes []Index
	// referencedBy are the references other tables make to this one, so a
	// delete or key update can find them without scanning the catalog.
	//
	// It is unexported and reached only through the methods below, because the
	// binder appends to it while CREATE TABLE runs and the executor reads it
	// while a concurrent DELETE runs. A shared engine behind a connection pool
	// makes that a real data race, so the slice must never escape the lock.
	referencedBy []Referencing
	// refsMu guards referencedBy. It is separate from mu, which the per-insert
	// serial path takes, so a foreign-key read does not queue behind sequence
	// allocation.
	refsMu sync.RWMutex
	// defaultEval evaluates a DEFAULT expression; see SetDefaultEvaluator.
	defaultEval DefaultEvaluator
	// predCompiler compiles a partial index predicate; see
	// SetPredicateCompiler.
	predCompiler PredicateCompiler
	// byName resolves a column name to its ordinal. Every reference below the
	// binder is an ordinal; this map is consulted during binding only.
	byName map[string]int

	// heap holds every version of every row. Storage is versioned rather than
	// overwritten so that a reader keeps seeing what was current when its
	// snapshot was taken, and so that rollback is one flag rather than an undo
	// log; see internal/storage.
	heap *storage.Heap

	// mu guards the sequence counters only. Row access is guarded by the heap.
	mu sync.Mutex
	// nextSerial holds the next value for each serial column, keyed by ordinal.
	// A sequence is per column rather than global so that truncating one table
	// cannot disturb another.
	//
	// Sequences deliberately sit outside the transaction: a rolled back INSERT
	// still consumes its value, exactly as in PostgreSQL, because handing the
	// same id to a later transaction would be worse than a gap.
	nextSerial map[int]int64
}

// QualifiedName returns the schema-qualified name, as it appears in errors.
func (t *Table) QualifiedName() string { return t.Schema + "." + t.Name }

// ColumnIndex returns the ordinal of a column, or -1 if there is none.
func (t *Table) ColumnIndex(name string) int {
	if i, ok := t.byName[name]; ok {
		return i
	}
	return -1
}

// Insert adds a row on behalf of a transaction.
//
// The row must already be the right width and coerced to each column's type by
// the binder.
func (t *Table) Insert(tx *storage.Tx, row []types.Value) error {
	if err := t.checkRow(row); err != nil {
		return err
	}
	v := t.heap.Insert(tx.ID, row)
	// The row is logged rather than copied first because a version's values are
	// never mutated once it is linked in, which is the same property that lets
	// a reader hold one without copying.
	tx.Log(wal.InsertRecord(t.QualifiedName(), uint64(v.ID), row))
	return nil
}

// Load places a row read back from the log, with the id it was written under.
//
// Recovery uses this instead of Insert: the id is given rather than allocated,
// the constraints were checked when the row was first written, and nothing is
// logged -- writing back what was just read would double the log on every
// restart.
func (t *Table) Load(tx *storage.Tx, id storage.RowID, row []types.Value) {
	t.heap.Load(tx.ID, id, row)
}

// Scan returns the row versions visible to a transaction.
//
// Versions are returned rather than bare rows because a statement that goes on
// to update or delete a row needs to name the version it read; a row's values
// alone do not identify it.
func (t *Table) Scan(tx *storage.Tx) []*storage.Version {
	return t.heap.Scan(tx.Snapshot(), tx.ID)
}

// Rows returns the values visible to a transaction, for callers that only read.
func (t *Table) Rows(tx *storage.Tx) [][]types.Value {
	versions := t.Scan(tx)
	out := make([][]types.Value, len(versions))
	for i, v := range versions {
		out[i] = t.Values(v)
	}
	return out
}

// Values returns a version's row at the table's current width.
//
// A row written before an ADD COLUMN is shorter than the table, and the columns
// it lacks read as their Missing value. Every read of a stored row goes through
// here rather than touching Vals directly, because a short row reaching an
// expression that addresses the new column is an out-of-range panic rather than
// a wrong answer.
//
// The common case -- no column was ever added -- returns the stored slice
// untouched, so this costs a length comparison.
func (t *Table) Values(v *storage.Version) []types.Value {
	if len(v.Vals) == len(t.Columns) {
		return v.Vals
	}
	out := make([]types.Value, len(t.Columns))
	copy(out, v.Vals)
	for i := len(v.Vals); i < len(t.Columns); i++ {
		out[i] = t.Columns[i].Missing
	}
	return out
}

// Update replaces a row version with new values.
//
// The old version is marked deleted by this transaction and a new one is
// written, so a reader on an older snapshot still sees the old values.
func (t *Table) Update(tx *storage.Tx, old *storage.Version, vals []types.Value) error {
	if err := t.checkRow(vals); err != nil {
		return err
	}
	if err := t.heap.Delete(tx.ID, old); err != nil {
		return err
	}
	v := t.heap.Insert(tx.ID, vals)
	name := t.QualifiedName()
	tx.Log(wal.DeleteRecord(name, uint64(old.ID)))
	tx.Log(wal.InsertRecord(name, uint64(v.ID), vals))
	return nil
}

// Delete removes a row version.
func (t *Table) Delete(tx *storage.Tx, v *storage.Version) error {
	if err := t.heap.Delete(tx.ID, v); err != nil {
		return err
	}
	tx.Log(wal.DeleteRecord(t.QualifiedName(), uint64(v.ID)))
	return nil
}

// SetMissing fixes the value short rows take for a column, when recovery reads
// it back from the log.
//
// ADD COLUMN evaluates the column's DEFAULT once, at the moment it runs. While
// only a constant DEFAULT is accepted, replaying the statement recomputes the
// same value and this changes nothing; see wal.Missing for why the log records
// it regardless.
func (t *Table) SetMissing(ordinal int, v types.Value) error {
	if ordinal < 0 || ordinal >= len(t.Columns) {
		return pgerr.Newf(pgerr.DataCorrupted,
			"table %q has no column %d to restore a missing value for", t.QualifiedName(), ordinal)
	}
	t.Columns[ordinal].Missing = v
	return nil
}

// RestoreSequences sets each serial column's counter past the largest value the
// table holds.
//
// A sequence is not itself logged: it sits outside the transaction, so logging
// each allocation would mean writing a record for a statement that then rolls
// back. Deriving it from the rows on restart gives the one property that
// matters, which is that the next value allocated collides with nothing. It can
// hand back a number that a deleted row once used, which PostgreSQL would not
// do; the gap-free alternative is a record per allocation.
func (t *Table) RestoreSequences(tx *storage.Tx) {
	t.mu.Lock()
	defer t.mu.Unlock()

	for ord := range t.Columns {
		if !t.Columns[ord].Type.Serial {
			continue
		}
		var high int64
		for _, row := range t.Rows(tx) {
			if v := row[ord]; v.Kind() == types.KindInt && v.AsInt() > high {
				high = v.AsInt()
			}
		}
		if high > 0 {
			if t.nextSerial == nil {
				t.nextSerial = make(map[int]int64)
			}
			t.nextSerial[ord] = high + 1
		}
	}
}

// EvalDefault produces a column's DEFAULT value.
//
// This is for SET DEFAULT, which needs the value outside the binder's usual
// path: a referential action has no statement of its own to bind against. The
// expression is bound and evaluated here in an empty scope, exactly as an
// omitted column in an INSERT would be.
func (t *Table) EvalDefault(ordinal int) (types.Value, error) {
	col := t.Columns[ordinal]
	if col.Default == nil {
		return types.Null(), nil
	}
	if t.defaultEval == nil {
		return types.Null(), pgerr.Newf(pgerr.InternalError,
			"no default evaluator installed for %q", t.Name)
	}
	return t.defaultEval(col.Default, col.Type.Kind)
}

// SetDefaultEvaluator installs the function that turns a written DEFAULT
// expression into a value.
//
// The catalog stores defaults as syntax and cannot evaluate them itself — the
// binder and executor both sit above it. Rather than invert that dependency,
// the engine hands the catalog a closure at startup.
func (c *Catalog) SetDefaultEvaluator(fn DefaultEvaluator) { c.defaultEval = fn }

// DefaultEvaluator binds and evaluates a DEFAULT expression for a column type.
type DefaultEvaluator func(expr ast.Expr, want types.Kind) (types.Value, error)

// SetPredicateCompiler installs the function that turns a written predicate
// into something the catalog can run over a row.
//
// A partial index needs its WHERE clause evaluated while uniqueness is being
// checked, and the catalog can no more bind a predicate than it can a DEFAULT.
// The closure compiles once per check rather than per row, so a partial index
// over a large table does not re-bind its predicate for every row.
func (c *Catalog) SetPredicateCompiler(fn PredicateCompiler) { c.predCompiler = fn }

// PredicateCompiler binds a predicate against a table and returns a function
// that evaluates it over one row.
type PredicateCompiler func(expr ast.Expr, t *Table) (func(row []types.Value) (bool, error), error)

// CheckForeignKeys verifies that every row this transaction can see satisfies
// the table's outgoing references.
//
// It runs once at the end of a statement, like the uniqueness check, so a
// statement that temporarily points at a row it is about to insert is judged on
// where it ends up rather than on the order its rows happened to be written.
func (t *Table) CheckForeignKeys(tx *storage.Tx) error {
	if len(t.ForeignKeys) == 0 {
		return nil
	}
	for _, row := range t.Rows(tx) {
		for i := range t.ForeignKeys {
			if err := t.checkReference(tx, &t.ForeignKeys[i], row); err != nil {
				return err
			}
		}
	}
	return nil
}

// checkReference verifies one row against one foreign key.
func (t *Table) checkReference(tx *storage.Tx, fk *ForeignKey, row []types.Value) error {
	// A NULL anywhere in the key satisfies the constraint. This is SQL's MATCH
	// SIMPLE, the default: a reference that is not fully specified does not
	// point anywhere, so there is nothing for it to fail to match.
	if anyNull(row, fk.Columns) {
		return nil
	}
	if parentHasKey(tx, fk, row) {
		return nil
	}

	names := make([]string, len(fk.Columns))
	vals := make([]string, len(fk.Columns))
	for i, ord := range fk.Columns {
		names[i] = t.Columns[ord].Name
		vals[i] = row[ord].String()
	}
	return pgerr.Newf(pgerr.ForeignKeyViolation,
		"insert or update on table %q violates foreign key constraint %q", t.Name, fk.Name).
		WithDetail("Key (%s)=(%s) is not present in table %q.",
			strings.Join(names, ", "), strings.Join(vals, ", "), fk.Parent.Name)
}

// parentHasKey reports whether the referenced table holds a row matching the
// child's key, as seen by this transaction.
//
// It is a scan of the parent per row checked. There are no indexes yet, so the
// cost of an insert is proportional to the parent table; an index on the
// referenced columns is the first thing that would fix it.
func parentHasKey(tx *storage.Tx, fk *ForeignKey, child []types.Value) bool {
	for _, prow := range fk.Parent.Rows(tx) {
		if matchesKey(child, fk.Columns, prow, fk.ParentCols) {
			return true
		}
	}
	return false
}

// matchesKey reports whether two rows agree across a pair of column lists.
func matchesKey(a []types.Value, aCols []int, b []types.Value, bCols []int) bool {
	for i, ord := range aCols {
		if !types.Equal(a[ord], b[bCols[i]]) {
			return false
		}
	}
	return true
}

// ChildrenOf returns the rows of referencing tables that point at the given
// parent row, grouped by the reference that found them.
func (t *Table) ChildrenOf(tx *storage.Tx, parent []types.Value) []ChildRows {
	t.refsMu.RLock()
	defer t.refsMu.RUnlock()

	var out []ChildRows
	for _, ref := range t.referencedBy {
		var rows []*storage.Version
		for _, v := range ref.Child.Scan(tx) {
			vals := ref.Child.Values(v)
			if anyNull(vals, ref.FK.Columns) {
				continue // an unspecified reference points at nothing
			}
			if matchesKey(vals, ref.FK.Columns, parent, ref.FK.ParentCols) {
				rows = append(rows, v)
			}
		}
		if len(rows) > 0 {
			out = append(out, ChildRows{Ref: ref, Rows: rows})
		}
	}
	return out
}

// AddReferencing records an incoming foreign key. The binder calls it while
// binding the child's CREATE TABLE, which can run concurrently with a statement
// on the parent.
func (t *Table) AddReferencing(r Referencing) {
	t.refsMu.Lock()
	defer t.refsMu.Unlock()
	t.referencedBy = append(t.referencedBy, r)
}

// IsReferenced reports whether any table points at this one, so a delete can
// skip the referential-action machinery entirely.
func (t *Table) IsReferenced() bool {
	t.refsMu.RLock()
	defer t.refsMu.RUnlock()
	return len(t.referencedBy) > 0
}

// ChildRows are the referencing rows found for one incoming foreign key.
type ChildRows struct {
	Ref  Referencing
	Rows []*storage.Version
}

// CheckConstraints validates the table's uniqueness constraints over the rows
// the transaction can now see.
//
// It runs once at the end of a statement rather than per row, which is what
// PostgreSQL does by deferring the check. That matters twice over: a row keeping
// its own value must not conflict with itself, and `UPDATE t SET a = a + 1`
// passes through states that collide but ends in one that does not.
func (t *Table) CheckConstraints(tx *storage.Tx) error {
	if len(t.Constraints) == 0 && !t.hasUniqueIndex() {
		return nil
	}
	return t.checkUnique(t.Rows(tx))
}

func (t *Table) hasUniqueIndex() bool {
	for _, ix := range t.Indexes {
		if ix.Unique {
			return true
		}
	}
	return false
}

// checkRow enforces the per-row constraints. The caller must hold the write
// lock.
func (t *Table) checkRow(row []types.Value) error {
	for i := range t.Columns {
		col := &t.Columns[i]
		if col.NotNull && row[i].IsNull() {
			return pgerr.Newf(pgerr.NotNullViolation,
				"null value in column %q of relation %q violates not-null constraint",
				col.Name, t.Name)
		}
		if col.Type.Kind == types.KindNumeric && !row[i].IsNull() {
			v, err := fitNumeric(row[i], col)
			if err != nil {
				return err
			}
			row[i] = v
		}
	}
	return nil
}

// fitNumeric applies a numeric column's declared precision and scale to a value
// on its way in.
//
// This is what makes NUMERIC(10,2) an amount of money rather than a suggestion:
// the value is rounded to the declared scale, so what is stored is what the
// column promised, and a value too large for the declared precision is refused
// rather than silently kept at full width. PostgreSQL does both at assignment,
// and doing it here rather than in the binder covers every path that writes a
// row -- insert, update, a DEFAULT, a referential SET DEFAULT -- instead of the
// ones someone remembered.
//
// A numeric declared without precision, plain NUMERIC, constrains nothing and
// keeps whatever it was given, again as in PostgreSQL.
func fitNumeric(v types.Value, col *Column) (types.Value, error) {
	if len(col.Type.Mods) < 2 {
		return v, nil
	}
	precision, scale := col.Type.Mods[0], col.Type.Mods[1]

	d := v.AsDecimal().Round(int32(scale))
	// The digits left of the point are what the precision limits, so the check
	// is against precision minus scale rather than against precision.
	if digitsBefore(d) > precision-scale {
		return types.Value{}, pgerr.Newf(pgerr.NumericValueOutOfRange,
			"numeric field overflow").
			WithDetail("A field with precision %d, scale %d must round to an absolute value less than 10^%d.",
				precision, scale, precision-scale)
	}
	return types.Numeric(d), nil
}

// digitsBefore counts the digits to the left of the point, which is zero for a
// value smaller than one.
func digitsBefore(d *types.Decimal) int {
	text := d.String()
	text = strings.TrimPrefix(text, "-")
	whole, _, _ := strings.Cut(text, ".")
	if whole == "0" {
		return 0
	}
	return len(whole)
}

// checkUnique verifies every uniqueness constraint over a whole row set.
//
// The update path validates the result as a whole rather than testing each
// changed row against the others, which is what PostgreSQL does by deferring the
// check to the end of the statement. That matters twice over: a row keeping its
// own value must not conflict with itself, and `UPDATE t SET a = a + 1` passes
// through states that collide but ends in a state that does not.
//
// The caller must hold the write lock.
func (t *Table) checkUnique(rows [][]types.Value) error {
	for _, c := range t.Constraints {
		if err := t.checkUniqueOver(rows, c.Columns, nil, func(row []types.Value) error {
			return t.uniqueViolation(c, row)
		}); err != nil {
			return err
		}
	}

	for _, ix := range t.Indexes {
		if !ix.Unique {
			continue
		}
		// A partial index constrains only the rows its predicate selects, so
		// the predicate is compiled once here and consulted per row. Compiling
		// per row would re-bind the same expression for every row of the table.
		var covers func(row []types.Value) (bool, error)
		if ix.Where != nil {
			if t.predCompiler == nil {
				return pgerr.Newf(pgerr.InternalError,
					"no predicate compiler installed for %q", t.Name)
			}
			var err error
			if covers, err = t.predCompiler(ix.Where, t); err != nil {
				return err
			}
		}
		if err := t.checkUniqueOver(rows, ix.Columns, covers, func(row []types.Value) error {
			return t.indexViolation(ix, row)
		}); err != nil {
			return err
		}
	}
	return nil
}

// checkUniqueOver verifies that no two covered rows agree on the key columns.
//
// covers is nil for a total constraint and reports membership for a partial
// one. Rows are grouped by hash so the check is linear rather than quadratic;
// candidates in a bucket are still compared properly, since a hash collision is
// not a duplicate.
func (t *Table) checkUniqueOver(
	rows [][]types.Value,
	cols []int,
	covers func(row []types.Value) (bool, error),
	violation func(row []types.Value) error,
) error {
	// Rows are grouped by hash so the check is linear rather than quadratic.
	// The candidates in a bucket are still compared properly, since a hash
	// collision is not a duplicate.
	buckets := make(map[uint64][]int, len(rows))
	seed := maphash.MakeSeed()

	for i, row := range rows {
		// A NULL is never equal to anything, including another NULL, so a row
		// with a NULL in any key column cannot violate the constraint. This is
		// why UNIQUE permits any number of NULLs — the single most surprising
		// rule in this area, and one that using the grouping form of equality
		// would silently get wrong.
		if anyNull(row, cols) {
			continue
		}
		if covers != nil {
			// Only true selects a row, so a predicate that is false or unknown
			// leaves it outside the index — the same rule a WHERE clause
			// follows, and the reason a NULL column does not join a partial
			// index written about it.
			in, err := covers(row)
			if err != nil {
				return err
			}
			if !in {
				continue
			}
		}

		var h maphash.Hash
		h.SetSeed(seed)
		for _, ord := range cols {
			row[ord].Hash(&h)
		}
		sum := h.Sum64()

		for _, j := range buckets[sum] {
			if keyEqual(row, rows[j], cols) {
				return violation(row)
			}
		}
		buckets[sum] = append(buckets[sum], i)
	}
	return nil
}

func anyNull(row []types.Value, cols []int) bool {
	for _, ord := range cols {
		if row[ord].IsNull() {
			return true
		}
	}
	return false
}

// keyEqual reports whether two rows agree on every key column. Only non-NULL
// rows reach here, so the grouping form of equality is the right one.
func keyEqual(a, b []types.Value, cols []int) bool {
	for _, ord := range cols {
		if !types.Equal(a[ord], b[ord]) {
			return false
		}
	}
	return true
}

// uniqueViolation builds the error, mirroring PostgreSQL's wording so that a
// parity test can compare the two.
func (t *Table) uniqueViolation(c Constraint, row []types.Value) error {
	names := make([]string, len(c.Columns))
	vals := make([]string, len(c.Columns))
	for i, ord := range c.Columns {
		names[i] = t.Columns[ord].Name
		vals[i] = row[ord].String()
	}
	return pgerr.Newf(pgerr.UniqueViolation,
		"duplicate key value violates unique constraint %q", c.Name).
		WithDetail("Key (%s)=(%s) already exists.",
			strings.Join(names, ", "), strings.Join(vals, ", "))
}

// indexViolation reports a duplicate in a unique index. PostgreSQL words this
// the same as a unique constraint, since an index is how it enforces one.
func (t *Table) indexViolation(ix Index, row []types.Value) error {
	names := make([]string, len(ix.Columns))
	vals := make([]string, len(ix.Columns))
	for i, ord := range ix.Columns {
		names[i] = t.Columns[ord].Name
		vals[i] = row[ord].String()
	}
	return pgerr.Newf(pgerr.UniqueViolation,
		"duplicate key value violates unique constraint %q", ix.Name).
		WithDetail("Key (%s)=(%s) already exists.",
			strings.Join(names, ", "), strings.Join(vals, ", "))
}

// NextSerial returns and consumes the next value of a serial column.
func (t *Table) NextSerial(ordinal int) int64 {
	t.mu.Lock()
	defer t.mu.Unlock()

	if t.nextSerial == nil {
		t.nextSerial = make(map[int]int64)
	}
	n := t.nextSerial[ordinal]
	if n == 0 {
		n = 1 // sequences start at 1, matching PostgreSQL
	}
	t.nextSerial[ordinal] = n + 1
	return n
}

// Catalog is the set of tables in one database instance.
type Catalog struct {
	// mgr is handed to each table's heap so that visibility is judged
	// consistently across the whole instance.
	mgr *storage.TxManager
	// defaultEval is handed to each table so SET DEFAULT can produce a value.
	defaultEval DefaultEvaluator
	// predCompiler is handed to each table so a partial index can be enforced.
	predCompiler PredicateCompiler

	mu     sync.RWMutex
	tables map[string]*Table
}

// New returns an empty catalog whose tables share one transaction manager.
func New(mgr *storage.TxManager) *Catalog {
	return &Catalog{mgr: mgr, tables: make(map[string]*Table)}
}

func key(schema, name string) string { return schema + "." + name }

// checkWritableRelation refuses a schema change aimed at a computed catalog.
//
// Without it these report that the relation does not exist, which is both
// untrue and misleading: it does exist and can be selected from, so being told
// it is missing sends the reader looking in the wrong place.
//
// It must be called with the schema as written, before any defaulting to
// public. An unqualified name reaches pg_catalog first when it is read -- that
// is what makes `FROM pg_tables` work -- so defaulting first would let
// `ALTER TABLE pg_tables` past the guard and then fail to find a table called
// public.pg_tables, which is the confusing message this exists to prevent.
func (c *Catalog) checkWritableRelation(schema, name string) error {
	if v, ok := c.LookupSystemView(schema, name); ok {
		return deniedError(v.QualifiedName())
	}
	if IsSystemSchema(schema) {
		return deniedError(Qualify(schema, name))
	}
	return nil
}

func deniedError(qualified string) error {
	return pgerr.Newf(pgerr.InvalidSchemaName,
		"permission denied to change %q", qualified).
		WithDetail("System catalog modifications are currently disallowed.")
}

// Qualify returns the name a table is known by, defaulting an empty schema.
//
// It is the counterpart of LookupQualified, and exists so that a caller outside
// the catalog cannot build the string a different way: a log record and the map
// it will be looked up in have to agree exactly.
func Qualify(schema, name string) string {
	if schema == "" {
		schema = DefaultSchema
	}
	return key(schema, name)
}

// CreateTable registers a new table. It reports a duplicate as a
// DuplicateTable error unless ifNotExists is set, in which case an existing
// table is left alone and created reports false.
func (c *Catalog) CreateTable(t *Table, ifNotExists bool) (created bool, err error) {
	// A table in a computed schema would be unreachable: a name there resolves
	// to the view, so the table could be created and then never selected from.
	// PostgreSQL refuses for the same reason.
	if err := c.checkWritableRelation(t.Schema, t.Name); err != nil {
		return false, err
	}
	if t.Schema == "" {
		t.Schema = DefaultSchema
	}
	if err := t.index(); err != nil {
		return false, err
	}
	t.heap = storage.NewHeap(c.mgr)
	t.defaultEval = c.defaultEval
	t.predCompiler = c.predCompiler

	c.mu.Lock()
	defer c.mu.Unlock()

	k := key(t.Schema, t.Name)
	if _, exists := c.tables[k]; exists {
		if ifNotExists {
			return false, nil
		}
		return false, pgerr.Newf(pgerr.DuplicateTable, "relation %q already exists", t.Name)
	}
	c.tables[k] = t

	// Register the incoming references only now, with the table complete and in
	// the catalog. Doing it during binding published a half-built table — one
	// whose heap was not yet assigned — to any statement already walking the
	// parent's children. Taking the address of the slice element rather than of
	// a local also means the parent and the child share one foreign key, so a
	// later change to it cannot be seen by only one of them.
	for i := range t.ForeignKeys {
		fk := &t.ForeignKeys[i]
		fk.Parent.AddReferencing(Referencing{Child: t, FK: fk})
	}
	return true, nil
}

// index builds the name lookup and rejects duplicate column names.
func (t *Table) index() error {
	t.byName = make(map[string]int, len(t.Columns))
	for i := range t.Columns {
		name := t.Columns[i].Name
		if _, dup := t.byName[name]; dup {
			return pgerr.Newf(pgerr.DuplicateColumn,
				"column %q specified more than once", name)
		}
		t.byName[name] = i
	}
	return nil
}

// AddColumn appends a column to a table.
//
// The rows already stored are left as they are. They are shorter than the table
// from now on, and read the new column as missing -- see Column.Missing and
// Values. Rewriting them instead would mean mutating values a reader may be
// holding, which the heap does not allow.
func (c *Catalog) AddColumn(t *Table, col *Column, missing types.Value, check *Check, fk *ForeignKey, ifNotExists bool) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if _, exists := t.byName[col.Name]; exists {
		if ifNotExists {
			return nil
		}
		return pgerr.Newf(pgerr.DuplicateColumn,
			"column %q of relation %q already exists", col.Name, t.Name)
	}

	col.Missing = missing
	t.Columns = append(t.Columns, *col)
	t.byName[col.Name] = len(t.Columns) - 1

	if check != nil {
		t.Checks = append(t.Checks, *check)
	}
	if fk != nil {
		t.ForeignKeys = append(t.ForeignKeys, *fk)
		// Registered only once the column is in place, for the same reason
		// CreateTable waits: publishing a reference to a half-built table lets
		// a concurrent statement walk into it. Taking the address of the slice
		// element keeps parent and child sharing one foreign key.
		added := &t.ForeignKeys[len(t.ForeignKeys)-1]
		added.Parent.AddReferencing(Referencing{Child: t, FK: added})
	}
	return nil
}

// RenameTable renames a table, moving it to its new key.
//
// Nothing else has to change: a foreign key holds a *Table rather than a name,
// so a reference survives the rename without being rewritten. That is the
// payoff of resolving names once, at bind time.
func (c *Catalog) RenameTable(schema, from, to string) error {
	if err := c.checkWritableRelation(schema, from); err != nil {
		return err
	}
	if schema == "" {
		schema = DefaultSchema
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	t, ok := c.tables[key(schema, from)]
	if !ok {
		return pgerr.Newf(pgerr.UndefinedTable, "relation %q does not exist", from)
	}
	if from == to {
		return nil
	}
	if _, taken := c.tables[key(schema, to)]; taken {
		return pgerr.Newf(pgerr.DuplicateTable, "relation %q already exists", to)
	}

	delete(c.tables, key(schema, from))
	t.Name = to
	c.tables[key(schema, to)] = t
	return nil
}

// RenameColumn renames one column of a table.
//
// Only the name changes. Every reference below the binder is an ordinal, so no
// stored row and no constraint needs rewriting -- but the name lookup the binder
// consults does, or the new name would not resolve.
func (c *Catalog) RenameColumn(schema, table, from, to string) error {
	if err := c.checkWritableRelation(schema, table); err != nil {
		return err
	}
	if schema == "" {
		schema = DefaultSchema
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	t, ok := c.tables[key(schema, table)]
	if !ok {
		return pgerr.Newf(pgerr.UndefinedTable, "relation %q does not exist", table)
	}
	i, ok := t.byName[from]
	if !ok {
		return pgerr.Newf(pgerr.UndefinedColumn,
			"column %q of relation %q does not exist", from, table)
	}
	if from == to {
		return nil
	}
	if _, taken := t.byName[to]; taken {
		return pgerr.Newf(pgerr.DuplicateColumn,
			"column %q of relation %q already exists", to, table)
	}
	if what := t.dependsOnColumnName(from); what != "" {
		// CHECK predicates, DEFAULT expressions and partial index predicates
		// are stored as syntax, so they name the column rather than addressing
		// it by ordinal. Renaming without rewriting them leaves the table
		// un-insertable, failing on a column the schema no longer shows --
		// which is far worse than refusing the rename.
		return pgerr.Newf(pgerr.FeatureNotSupported,
			"cannot rename column %q of relation %q because %s refers to it by name",
			from, table, what)
	}

	t.Columns[i].Name = to
	delete(t.byName, from)
	t.byName[to] = i
	return nil
}

// SetNotNull adds or removes a column's NOT NULL constraint.
//
// Adding one is checked against the rows the transaction can see, because the
// constraint has to be true of what is already stored before it can be promised
// about what comes next. This is the half of the "add nullable, backfill,
// tighten" migration that ADD COLUMN ... NOT NULL DEFAULT cannot do, since that
// gives every row the same constant.
//
// Removing one needs no check, with one exception: a primary key column is NOT
// NULL because it is part of the key, and dropping the flag would leave a
// constraint that says one thing and a column that says another.
func (c *Catalog) SetNotNull(tx *storage.Tx, schema, table, column string, notNull bool) error {
	if err := c.checkWritableRelation(schema, table); err != nil {
		return err
	}
	if schema == "" {
		schema = DefaultSchema
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	t, ok := c.tables[key(schema, table)]
	if !ok {
		return pgerr.Newf(pgerr.UndefinedTable, "relation %q does not exist", table)
	}
	ord, ok := t.byName[column]
	if !ok {
		return pgerr.Newf(pgerr.UndefinedColumn,
			"column %q of relation %q does not exist", column, table)
	}
	if t.Columns[ord].NotNull == notNull {
		return nil
	}

	if !notNull {
		if t.Columns[ord].PrimaryKey {
			return pgerr.Newf(pgerr.InvalidTableDefinition,
				"column %q is in a primary key", column)
		}
		t.Columns[ord].NotNull = false
		return nil
	}

	// Every row is checked, including the ones shorter than the table: Values
	// pads them with what the column records for rows written before it
	// existed, and that value is as much subject to the constraint as any
	// other.
	for _, v := range t.Scan(tx) {
		if t.Values(v)[ord].IsNull() {
			return pgerr.Newf(pgerr.NotNullViolation,
				"column %q of relation %q contains null values", column, table)
		}
	}
	t.Columns[ord].NotNull = true
	return nil
}

// CreateIndex adds an index to a table.
//
// Index names live in one namespace per schema, as in PostgreSQL, so a name
// already taken on another table is a conflict rather than a shadowing.
func (c *Catalog) CreateIndex(schema, table string, ix Index, ifNotExists bool) (created bool, err error) {
	if err := c.checkWritableRelation(schema, table); err != nil {
		return false, err
	}
	if schema == "" {
		schema = DefaultSchema
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	for _, t := range c.tables {
		if t.Schema != schema {
			continue
		}
		for _, existing := range t.Indexes {
			if existing.Name == ix.Name {
				if ifNotExists {
					return false, nil
				}
				return false, pgerr.Newf(pgerr.DuplicateTable,
					"relation %q already exists", ix.Name)
			}
		}
	}

	t, ok := c.tables[key(schema, table)]
	if !ok {
		return false, pgerr.Newf(pgerr.UndefinedTable, "relation %q does not exist", table)
	}
	t.Indexes = append(t.Indexes, ix)
	return true, nil
}

// DropIndex removes an index by name.
func (c *Catalog) DropIndex(schema, name string, ifExists bool) error {
	if schema == "" {
		schema = DefaultSchema
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	for _, t := range c.tables {
		if t.Schema != schema {
			continue
		}
		if i := slices.IndexFunc(t.Indexes, func(ix Index) bool { return ix.Name == name }); i >= 0 {
			t.Indexes = slices.Delete(t.Indexes, i, i+1)
			return nil
		}
	}
	if ifExists {
		return nil
	}
	return pgerr.Newf(pgerr.UndefinedTable, "index %q does not exist", name)
}

// QualifiedName is a table name as written, before the default schema is
// applied.
type QualifiedName struct {
	Schema, Name string
}

// DropTable removes tables from the catalog.
//
// The whole set goes at once rather than one at a time, because a reference
// between two of the named tables is not a reason to refuse: `DROP TABLE parent,
// child` is legal even though dropping the parent on its own would not be.
//
// A table still referenced from outside the set is refused, which is SQL's
// RESTRICT default. Dropping one regardless would leave the referencing table
// enforcing a constraint against a relation nobody can look up.
func (c *Catalog) DropTable(names []QualifiedName, ifExists bool) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	going := make(map[string]*Table, len(names))
	for _, n := range names {
		if err := c.checkWritableRelation(n.Schema, n.Name); err != nil {
			return err
		}
		schema := n.Schema
		if schema == "" {
			schema = DefaultSchema
		}
		t, ok := c.tables[key(schema, n.Name)]
		if !ok {
			if ifExists {
				continue
			}
			return pgerr.Newf(pgerr.UndefinedTable, "relation %q does not exist", n.Name)
		}
		going[key(schema, n.Name)] = t
	}

	for _, t := range going {
		if dep := t.referencedFromOutside(going); dep != "" {
			return pgerr.Newf(pgerr.ForeignKeyViolation,
				"cannot drop table %q because table %q depends on it", t.Name, dep)
		}
	}

	for k, t := range going {
		// Unregistering the table's own references matters as much as removing
		// it. A parent keeps a list of the children pointing at it, and leaving
		// a dropped child there would make a later DELETE from the parent
		// enforce a constraint against a table nobody can see.
		t.detach()
		delete(c.tables, k)
	}
	return nil
}

// referencedFromOutside names a table outside the given set that references t,
// or returns the empty string when none does.
func (t *Table) referencedFromOutside(going map[string]*Table) string {
	t.refsMu.RLock()
	defer t.refsMu.RUnlock()

	for _, ref := range t.referencedBy {
		if _, alsoGoing := going[key(ref.Child.Schema, ref.Child.Name)]; !alsoGoing {
			return ref.Child.Name
		}
	}
	return ""
}

// detach removes t from the referencedBy list of every table it points at.
func (t *Table) detach() {
	for i := range t.ForeignKeys {
		parent := t.ForeignKeys[i].Parent
		// A self-reference lives on the table being dropped, so there is
		// nothing outside it to clean up.
		if parent == nil || parent == t {
			continue
		}
		parent.removeReferencing(t)
	}
}

// removeReferencing drops every reference made by child.
func (t *Table) removeReferencing(child *Table) {
	t.refsMu.Lock()
	defer t.refsMu.Unlock()

	t.referencedBy = slices.DeleteFunc(t.referencedBy, func(r Referencing) bool {
		return r.Child == child
	})
}

// LookupQualified finds a table by the name QualifiedName produces.
//
// Recovery needs it because a log record names a table with that string, and
// splitting it back into two parts would be guesswork: both halves are
// identifiers and either may contain a dot when it was written quoted. The
// catalog is keyed on the same string, so no splitting is required.
func (c *Catalog) LookupQualified(name string) (*Table, error) {
	c.mu.RLock()
	defer c.mu.RUnlock()

	t, ok := c.tables[name]
	if !ok {
		return nil, pgerr.Newf(pgerr.UndefinedTable, "relation %q does not exist", name)
	}
	return t, nil
}

// Lookup finds a table. An empty schema means the default schema.
func (c *Catalog) Lookup(schema, name string) (*Table, error) {
	if schema == "" {
		schema = DefaultSchema
	}
	c.mu.RLock()
	defer c.mu.RUnlock()

	t, ok := c.tables[key(schema, name)]
	if !ok {
		return nil, pgerr.Newf(pgerr.UndefinedTable, "relation %q does not exist", name)
	}
	return t, nil
}

// Tables returns every table, ordered by qualified name, for introspection.
func (c *Catalog) Tables() []*Table {
	c.mu.RLock()
	defer c.mu.RUnlock()

	out := make([]*Table, 0, len(c.tables))
	for _, t := range c.tables {
		out = append(out, t)
	}
	// A stable order keeps introspection output deterministic across runs,
	// which map iteration would not.
	slices.SortFunc(out, func(a, b *Table) int {
		return cmp.Compare(a.QualifiedName(), b.QualifiedName())
	})
	return out
}

// dependsOnColumnName names the first stored expression that mentions the given
// column by name, or returns the empty string when none does.
//
// These are the expressions the catalog keeps as syntax rather than as
// ordinals: a CHECK predicate, a DEFAULT, and a partial index's predicate.
// Everything else below the binder addresses a column by ordinal and so is
// unaffected by a rename.
func (t *Table) dependsOnColumnName(name string) string {
	for _, c := range t.Checks {
		if ast.ReferencesColumn(c.Expr, name) {
			if c.Name != "" {
				return "check constraint " + strconv.Quote(c.Name)
			}
			return "a check constraint"
		}
	}
	for i := range t.Columns {
		col := &t.Columns[i]
		if col.Default != nil && ast.ReferencesColumn(col.Default, name) {
			return "the default for column " + strconv.Quote(col.Name)
		}
	}
	for _, ix := range t.Indexes {
		if ix.Where != nil && ast.ReferencesColumn(ix.Where, name) {
			return "the predicate of index " + strconv.Quote(ix.Name)
		}
	}
	return ""
}
