package driver_test

import (
	"slices"
	"strings"
	"testing"
)

// schemaFixture is a table with one of everything the views report on.
var schemaFixture = []string{
	`CREATE TABLE users (
		id    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		email VARCHAR(255) NOT NULL UNIQUE,
		note  TEXT DEFAULT 'none',
		made  TIMESTAMP DEFAULT now()
	)`,
	`CREATE TABLE posts (
		id     INT PRIMARY KEY,
		author INT NOT NULL REFERENCES users(id),
		CONSTRAINT posts_id_positive CHECK (id > 0)
	)`,
}

// TestGooseExistenceCheck is the query this feature exists for: a migration tool
// asking whether its own version table is there yet.
//
// It is written unqualified, which is the whole difficulty. PostgreSQL's
// implicit search_path puts pg_catalog ahead of everything the user wrote, so
// `FROM pg_tables` finds the view without a schema, and every tool written
// against PostgreSQL relies on that.
func TestGooseExistenceCheck(t *testing.T) {
	db := open(t)
	mustExecAll(t, db, schemaFixture...)

	for _, tt := range []struct {
		table string
		want  bool
	}{{"users", true}, {"goose_db_version", false}} {
		var got bool
		err := db.QueryRow(
			`SELECT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = $1)`, tt.table).Scan(&got)
		if err != nil {
			t.Fatalf("existence check for %q: %v", tt.table, err)
		}
		if got != tt.want {
			t.Errorf("EXISTS for %q = %v, want %v", tt.table, got, tt.want)
		}
	}
}

// TestInformationSchemaColumns covers what a code generator reads: the shape of
// a table, in declaration order, with the details that decide which Go type it
// maps to.
func TestInformationSchemaColumns(t *testing.T) {
	db := open(t)
	mustExecAll(t, db, schemaFixture...)

	got := rowsOf(t, db, `
		SELECT column_name, data_type, is_nullable, column_default, is_identity
		FROM information_schema.columns
		WHERE table_schema = 'public' AND table_name = 'users'
		ORDER BY ordinal_position`)

	want := []string{
		"id|integer|NO|NULL|YES",
		"email|character varying|NO|NULL|NO",
		"note|text|YES|'none'|NO",
		"made|timestamp without time zone|YES|now()|NO",
	}
	if !slices.Equal(got, want) {
		t.Errorf("columns =\n  %v\nwant\n  %v", got, want)
	}

	// The declared length is what tells a generator whether a string is bounded.
	length := rowsOf(t, db, `
		SELECT character_maximum_length FROM information_schema.columns
		WHERE table_name = 'users' AND column_name = 'email'`)
	if !slices.Equal(length, []string{"255"}) {
		t.Errorf("character_maximum_length = %v, want [255]", length)
	}
}

// TestInformationSchemaConstraints covers the two constraint views together,
// since a reader uses them together: one says a constraint exists, the other
// says which columns it covers.
func TestInformationSchemaConstraints(t *testing.T) {
	db := open(t)
	mustExecAll(t, db, schemaFixture...)

	got := rowsOf(t, db, `
		SELECT constraint_name, constraint_type
		FROM information_schema.table_constraints
		WHERE table_name = 'posts'
		ORDER BY constraint_type`)
	want := []string{
		"posts_id_positive|CHECK",
		"posts_author_fkey|FOREIGN KEY",
		"posts_pkey|PRIMARY KEY",
	}
	if !slices.Equal(got, want) {
		t.Errorf("constraints =\n  %v\nwant\n  %v", got, want)
	}

	keys := rowsOf(t, db, `
		SELECT constraint_name, column_name, ordinal_position
		FROM information_schema.key_column_usage
		WHERE table_name = 'posts'
		ORDER BY constraint_name`)
	if wantKeys := []string{"posts_author_fkey|author|1", "posts_pkey|id|1"}; !slices.Equal(keys, wantKeys) {
		t.Errorf("key usage =\n  %v\nwant\n  %v", keys, wantKeys)
	}
}

// TestCatalogViewsFollowTheCatalog pins that the rows are computed on read
// rather than captured. A prepared statement has to see a table created after
// it was prepared, which is exactly the case a migration tool hits: it prepares
// its existence check, creates the table, and asks again.
func TestCatalogViewsFollowTheCatalog(t *testing.T) {
	db := open(t)

	stmt, err := db.Prepare(`SELECT count(*) FROM pg_tables WHERE tablename = 'late'`)
	if err != nil {
		t.Fatalf("Prepare: %v", err)
	}
	defer stmt.Close()

	var before, after int
	if err := stmt.QueryRow().Scan(&before); err != nil {
		t.Fatalf("before: %v", err)
	}
	mustExecAll(t, db, `CREATE TABLE late (a INT)`)
	if err := stmt.QueryRow().Scan(&after); err != nil {
		t.Fatalf("after: %v", err)
	}

	if before != 0 || after != 1 {
		t.Errorf("count before = %d and after = %d, want 0 then 1", before, after)
	}
}

// TestCatalogViewsAreReadOnly pins that every way of changing one is refused,
// and refused by name.
//
// Reporting that the relation does not exist would be both untrue and
// misleading: it does exist and can be selected from, so being told it is
// missing sends the reader looking in the wrong place.
func TestCatalogViewsAreReadOnly(t *testing.T) {
	db := open(t)
	mustExecAll(t, db, schemaFixture...)

	tests := []struct {
		name string
		stmt string
	}{
		{"insert", `INSERT INTO pg_tables (tablename) VALUES ('x')`},
		{"update", `UPDATE pg_tables SET tablename = 'x'`},
		{"delete", `DELETE FROM information_schema.tables`},
		{"drop unqualified", `DROP TABLE pg_tables`},
		{"drop qualified", `DROP TABLE information_schema.tables`},
		{"rename", `ALTER TABLE pg_tables RENAME TO x`},
		{"add column", `ALTER TABLE pg_tables ADD COLUMN x INT`},
		{"set not null", `ALTER TABLE pg_tables ALTER COLUMN tablename SET NOT NULL`},
		{"create index", `CREATE INDEX ix ON pg_tables (tablename)`},
		// A table in a computed schema would be unreachable anyway: a name
		// there resolves to the view.
		{"create in pg_catalog", `CREATE TABLE pg_catalog.sneaky (a INT)`},
		{"create in information_schema", `CREATE TABLE information_schema.sneaky (a INT)`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := queryErr(db, tt.stmt)
			if err == nil {
				t.Fatalf("%s: expected an error", tt.stmt)
			}
			msg := err.Error()
			if strings.Contains(msg, "does not exist") {
				t.Errorf("%s\n got: %v\nwant it to say the view is read-only, not that it is missing", tt.stmt, err)
			}
			if !strings.Contains(msg, "pg_tables") && !strings.Contains(msg, "information_schema") &&
				!strings.Contains(msg, "pg_catalog") {
				t.Errorf("%s\n got: %v\nwant it to name the relation", tt.stmt, err)
			}
		})
	}
}

// TestInformationSchemaNeedsQualifying pins that an unqualified name does not
// reach information_schema, as it does not in PostgreSQL -- only pg_catalog is
// on the implicit search_path. A table of one's own called "tables" must keep
// working.
func TestInformationSchemaNeedsQualifying(t *testing.T) {
	db := open(t)

	if err := queryErr(db, `SELECT * FROM tables`); err == nil {
		t.Error("an unqualified name reached information_schema")
	}

	mustExecAll(t, db,
		`CREATE TABLE tables (a INT)`,
		`INSERT INTO tables VALUES (1)`,
	)
	if got := rowsOf(t, db, `SELECT a FROM tables`); !slices.Equal(got, []string{"1"}) {
		t.Errorf("a user table called tables reads %v, want [1]", got)
	}
}

// TestCatalogViewsJoin covers the views being ordinary relations to everything
// above the scan: they take an alias, join, filter and aggregate like any other.
func TestCatalogViewsJoin(t *testing.T) {
	db := open(t)
	mustExecAll(t, db, schemaFixture...)

	got := rowsOf(t, db, `
		SELECT t.table_name, count(c.column_name)
		FROM information_schema.tables t
		JOIN information_schema.columns c
		  ON c.table_schema = t.table_schema AND c.table_name = t.table_name
		WHERE t.table_schema = 'public'
		GROUP BY t.table_name
		ORDER BY t.table_name`)

	if want := []string{"posts|2", "users|4"}; !slices.Equal(got, want) {
		t.Errorf("joined counts = %v, want %v", got, want)
	}
}
