package driver_test

import (
	"slices"
	"testing"
	"time"
)

// TestGooseDialectStatements runs the statements goose's stock postgres dialect
// issues, in the order it issues them.
//
// It is hand-written rather than driven by goose itself, because taking a
// dependency on a migration tool to test a database is the wrong way round --
// and because the point is the SQL, not the library. What it buys is that the
// combination stays working: each statement here already passes for its own
// reasons, and every one of them was at some point the reason this did not work.
//
// The identity column, the unqualified pg_tables lookup and the
// schema-qualified table name were three separate gaps, found in that order,
// each hidden behind the one before it.
func TestGooseDialectStatements(t *testing.T) {
	db := open(t)

	// goose creates its version table with an identity column and a timestamp
	// default, schema-qualified.
	mustExecAll(t, db, `CREATE TABLE public.goose_db_version (
		id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		version_id bigint NOT NULL,
		is_applied boolean NOT NULL,
		tstamp     timestamp NOT NULL DEFAULT now()
	)`)

	// Before running anything it asks whether that table is there. Both forms
	// appear in the wild; the unqualified pg_tables one is the difficult case,
	// since it relies on pg_catalog being searched without being named.
	for _, q := range []string{
		`SELECT EXISTS (SELECT 1 FROM pg_tables
			WHERE tablename = 'goose_db_version' AND schemaname = 'public')`,
		`SELECT EXISTS (SELECT 1 FROM information_schema.tables
			WHERE table_name = 'goose_db_version' AND table_schema = 'public')`,
	} {
		var exists bool
		if err := db.QueryRow(q).Scan(&exists); err != nil {
			t.Fatalf("existence check: %v\n%s", err, q)
		}
		if !exists {
			t.Errorf("the version table was not found by:\n%s", q)
		}
	}

	// Applying a migration records it.
	for _, v := range []int64{1, 2, 3} {
		if _, err := db.Exec(
			`INSERT INTO public.goose_db_version (version_id, is_applied) VALUES ($1, $2)`,
			v, true); err != nil {
			t.Fatalf("recording version %d: %v", v, err)
		}
	}

	// Reading back what has been applied, newest first, is how goose decides
	// what is left to do.
	got := rowsOf(t, db,
		`SELECT id, version_id, is_applied FROM public.goose_db_version ORDER BY id DESC`)
	if want := []string{"3|3|true", "2|2|true", "1|1|true"}; !slices.Equal(got, want) {
		t.Errorf("applied versions = %v, want %v", got, want)
	}

	// The single-row lookup it uses for one version.
	var tstamp time.Time
	var applied bool
	err := db.QueryRow(`SELECT tstamp, is_applied FROM public.goose_db_version
		WHERE version_id = $1 ORDER BY tstamp DESC LIMIT 1`, 2).Scan(&tstamp, &applied)
	if err != nil {
		t.Fatalf("single version lookup: %v", err)
	}
	if !applied || tstamp.IsZero() {
		t.Errorf("version 2 reads applied=%v tstamp=%v, want true and a real time", applied, tstamp)
	}

	// And the highest applied version, which decides where "up" starts.
	if got := rowsOf(t, db, `SELECT MAX(version_id) FROM public.goose_db_version`); !slices.Equal(got, []string{"3"}) {
		t.Errorf("MAX(version_id) = %v, want [3]", got)
	}

	// Rolling one back removes its row.
	if _, err := db.Exec(`DELETE FROM public.goose_db_version WHERE version_id = $1`, 3); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if got := rowsOf(t, db, `SELECT MAX(version_id) FROM public.goose_db_version`); !slices.Equal(got, []string{"2"}) {
		t.Errorf("after a rollback MAX(version_id) = %v, want [2]", got)
	}
}
