package driver_test

import (
	"slices"
	"strings"
	"testing"
)

// TestIdentityByDefault covers the standard spelling of an auto-incrementing
// key. It is what SERIAL already does; the value of having both is that a
// schema written for another engine, or generated by a migration tool, does not
// have to be rewritten to run here.
//
// The statement below is verbatim the one goose creates its own version table
// with, which is where this came from.
func TestIdentityByDefault(t *testing.T) {
	db := open(t)
	mustExecAll(t, db, `CREATE TABLE goose_db_version (
		id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		version_id BIGINT NOT NULL,
		is_applied BOOLEAN NOT NULL,
		tstamp     TIMESTAMP NOT NULL DEFAULT now()
	)`)

	mustExecAll(t, db,
		`INSERT INTO goose_db_version (version_id, is_applied) VALUES (1, true)`,
		`INSERT INTO goose_db_version (version_id, is_applied) VALUES (2, true)`,
		// BY DEFAULT means the statement may supply its own value.
		`INSERT INTO goose_db_version (id, version_id, is_applied) VALUES (99, 3, true)`,
	)

	got := rowsOf(t, db, `SELECT id, version_id FROM goose_db_version ORDER BY id`)
	if want := []string{"1|1", "2|2", "99|3"}; !slices.Equal(got, want) {
		t.Errorf("rows = %v, want %v", got, want)
	}
}

// TestIdentityAlwaysRefusesAValue pins what distinguishes ALWAYS from BY
// DEFAULT. The column is an ordinary integer underneath, so accepting a value
// would work -- and would quietly hand back a table whose keys came from two
// places, which is the one thing the declaration ruled out.
func TestIdentityAlwaysRefusesAValue(t *testing.T) {
	db := open(t)
	mustExecAll(t, db,
		`CREATE TABLE t (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, nm TEXT)`,
		`INSERT INTO t (nm) VALUES ('a')`,
	)

	tests := []struct {
		name string
		stmt string
		want string
	}{
		{"named in the column list", `INSERT INTO t (id, nm) VALUES (5, 'b')`,
			"cannot insert a non-DEFAULT value"},
		// Without a column list every column is a target, so this supplies a
		// value for the identity column too. PostgreSQL refuses rather than
		// quietly skipping it.
		{"no column list", `INSERT INTO t VALUES (5, 'b')`,
			"cannot insert a non-DEFAULT value"},
		{"updated", `UPDATE t SET id = 7`, "can only be updated to DEFAULT"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := queryErr(db, tt.stmt)
			if err == nil {
				t.Fatalf("%s: expected an error", tt.stmt)
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Errorf("%s\n got: %v\nwant it to contain: %q", tt.stmt, err, tt.want)
			}
		})
	}

	// The rest of the row is still updatable, and the sequence still runs.
	mustExecAll(t, db,
		`UPDATE t SET nm = 'z'`,
		`INSERT INTO t (nm) VALUES ('c')`,
	)
	got := rowsOf(t, db, `SELECT id, nm FROM t ORDER BY id`)
	if want := []string{"1|z", "2|c"}; !slices.Equal(got, want) {
		t.Errorf("rows = %v, want %v", got, want)
	}
}

// TestIdentityImpliesNotNull pins the part of the declaration that is easy to
// leave out: an identity column always has a value, because the sequence
// supplies one when the statement does not.
func TestIdentityImpliesNotNull(t *testing.T) {
	db := open(t)
	mustExecAll(t, db, `CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY, nm TEXT)`)

	err := queryErr(db, `INSERT INTO t (id, nm) VALUES (NULL, 'a')`)
	if err == nil {
		t.Fatal("a null was accepted into an identity column")
	}
	if !strings.Contains(err.Error(), "not-null constraint") {
		t.Errorf("got %v, want a not-null violation", err)
	}
}

// TestIdentityErrors covers the declarations that are refused.
func TestIdentityErrors(t *testing.T) {
	db := open(t)

	tests := []struct {
		name string
		stmt string
		want string
	}{
		// PostgreSQL restricts identity to the integer types, and so does
		// this: a sequence produces integers, and a text column would silently
		// take their decimal spelling.
		{"wrong type", `CREATE TABLE t (id TEXT GENERATED ALWAYS AS IDENTITY)`,
			"must be smallint, integer or bigint"},
		// Ignoring START WITH would hand out the wrong first value, and
		// nothing about the schema would say why.
		{"sequence options", `CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY (START WITH 100))`,
			"sequence options"},
		{"neither always nor by default", `CREATE TABLE t (id INT GENERATED AS IDENTITY)`,
			"ALWAYS or BY DEFAULT"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := queryErr(db, tt.stmt)
			if err == nil {
				t.Fatalf("%s: expected an error", tt.stmt)
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Errorf("%s\n got: %v\nwant it to contain: %q", tt.stmt, err, tt.want)
			}
		})
	}
}
